### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by websterlincoln** [BMIRDS/deepslide#38]
```
python code/2_process_patches.py 
###############     CONFIGURATION     ###############
all_wsi:	all_wsi
val_wsi_per_class:	20
test_wsi_per_class:	30
keep_orig_copy:	True
num_workers:	8
patch_size:	224
wsi_train:	wsi_train
wsi_val:	wsi_val
wsi_test:	wsi_test
labels_train:	labels_train.csv
labels_val:	labels_val.csv
labels_test:	labels_test.csv
train_folder:	train_folder
patches_eval_train:	patches_eval_train
patches_eval_val:	patches_eval_val
patches_eval_test:	patches_eval_test
num_train_per_class:	80000
type_histopath:	True
purple_threshold:	100
purple_scale_size:	15
slide_overlap:	3
gen_val_patches_overlap_factor:	1.5
image_ext:	jpg
by_folder:	True
color_jitter_brightness:	0.5
color_jitter_contrast:	0.5
color_jitter_saturation:	0.5
color_jitter_hue:	0.2
num_epochs:	20
num_layers:	18
learning_rate:	0.001
batch_size:	16
weight_decay:	0.0001
learning_rate_decay:	0.85
resume_checkpoint:	False
save_interval:	1
checkpoints_folder:	checkpoints
checkpoint_file:	xyz.pt
pretrain:	False
log_folder:	logs
auto_select:	True
preds_train:	preds_train
preds_val:	preds_val
preds_test:	preds_test
inference_train:	inference_train
inference_val:	inference_val
inference_test:	inference_test
vis_train:	vis_train
vis_val:	vis_val
vis_test:	vis_test
device:	cuda:0
classes:	['0', '1', '2', '3', '4', '5']
num_classes:	6
train_patches:	train_folder/train
val_patches:	train_folder/val
path_mean:	[-2.5605530957943825e-20, 3.067582468253457e-41, 0.0]
path_std:	[nan, 0.0, 0.0]
resume_checkpoint_path:	checkpoints/xyz.pt
log_csv:	logs/log_8242021_121821.csv
eval_model:	checkpoints/xyz.pt
threshold_search:	(0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
colors:	('red', 'white', 'blue', 'green', 'purple', 'orange', 'black', 'pink', 'yellow')

#####################################################





+++++ Running 2_process_patches.py +++++

----- Generating training patches -----
[PosixPath('wsi_train/0'), PosixPath('wsi_train/1'), PosixPath('wsi_train/2'), PosixPath('wsi_train/3'), PosixPath('wsi_train/4'), PosixPath('wsi_train/5')] subfolders found from wsi_train
wsi_train/0: 106686.839468MB, 2842 images, overlap_factor=1.00
wsi_train/1: 103738.586958MB, 2616 images, overlap_factor=1.00
wsi_train/2: 46213.862613MB, 1293 images, overlap_factor=1.00
wsi_train/3: 33736.711066MB, 1192 images, overlap_factor=1.00
wsi_train/4: 18611.279527MB, 594 images, overlap_factor=1.00
Traceback (most recent call last):
  File "code/2_process_patches.py", line 20, in <module>
    type_histopath=config.args.type_histopath)
  File "/mnt/sda1/deepslide/code/utils_processing.py", line 140, in gen_train_patches
    subfolders=subfolders, desired_crops_per_class=num_train_per_class)
  File "/mnt/sda1/deepslide/code/utils_processing.py", line 107, in get_subfolder_to_overlap
    math.sqrt(desired_crops_per_class / (subfolder_size / 0.013)),
ZeroDivisionError: float division by zero
```

You may need to fix division occuring in utils_processing.py", line 107

**Comment by websterlincoln** [comment]
I guess the prroblem was the script stop rurnning, so one of the folders was empty. I guess you could implement a check to see if the folders have images
